server:
  port: 8088

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000

spring:
  datasource:
    # EX ) jdbc:mysql://localhost:{포트번호}/{데이터베이스 이름}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # ENC(암호화된 정보.)
    url: ENC(xo4fJn9bEUDl7KCZBBb1bgWUaoAkTzmdpSmmj4Udz+6uphfrWgXN/QdxF01AYDhuJGkHrWo1n+Y7/nNrUynOnUSi2QlyYCHOFmf3/n01sZx81T/7meGg3Ah7JGg+LCB5Xfnwsc+/VuPwO74W/o46WQ==)
    username: ENC(pZlyxUpO0dVsIU+SXZScNA==)
    password: ENC(jz/NnRh0Rf3sEHdHOLeXeA==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

    # Hibernate Configuration
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # paging setting
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true #paging => 1 start

logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace
